### ISSUE TITLE
Following the README for class_generator results in a failure when installing `openapi2jsonschema`

### ISSUE THREAD

**Issue by lugi0** [RedHatQE/openshift-python-wrapper#2202]
**Describe the bug**
When trying to set up the class_generator utility to use the `--update-schema` command the installation of `openapi2jsonschema` fails

**To Reproduce**
1. Run the command `uv tool install --python python3.9 openapi2jsonschema`

**Expected behavior**
`openapi2jsonschema` is installed, `--update-schema` can be used

**Additional context**
Full error: 
```
Resolved 5 packages in 1ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: pyyaml==5.4.1
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stdout]
running egg_info
writing lib3/PyYAML.egg-info/PKG-INFO
writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
writing top-level names to lib3/PyYAML.egg-info/top_level.txt

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 271, in <module>
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/dist.py", line 995, in run_command
    super().run_command(command)
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 313, in run
    self.find_sources()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in find_sources
    mm.run()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 544, in run
    self.add_defaults()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 582, in add_defaults
    sdist.add_defaults(self)
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
    super().add_defaults()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
    self._add_defaults_ext()
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
    self.filelist.extend(build_ext.get_source_files())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 201, in get_source_files
  File "/Users/lgiorgi/.cache/uv/builds-v0/.tmp0IKWa7/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources
```

**Comment by lugi0** [comment]
Related: https://github.com/astral-sh/uv/issues/1455

**Comment by myakove** [comment]
added workaround in the README 
https://github.com/RedHatQE/openshift-python-wrapper/pull/2203
